# Generated by Django 3.2.10 on 2022-04-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220420_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='secteur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
