# Generated by Django 3.2.10 on 2022-04-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220421_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='departement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
