# Generated by Django 3.2.10 on 2022-05-03 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_lieu_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='commentaire',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='RepCommentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.commentaire')),
            ],
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='user',
        ),
    ]
