# Generated by Django 3.2.10 on 2022-05-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_repcommentaire_reponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='desciption',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
