# Generated by Django 3.2.10 on 2022-05-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_lieu_desciption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lieu',
            old_name='desciption',
            new_name='description',
        ),
    ]
